language: python
python:
  - "2.7"
services: mysql
env:
  - DJANGO=1.4.3 DJANGO_SETTINGS_MODULE="voer.settings.travis"
install:
  - sudo apt-get install build-essential python2.7-dev python-dev python-pip
  - pip install -r requirements.txt
before_script:
  - mysql -e 'create database voer_django;'
  - python manage.travis.py syncdb --noinput
  - python manage.travis.py migrate vpw 
script:
  - python manage.travis.py test vpw.tests
